apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: r1oga/fib-calc-worker
      ports:
        - containerPort: 3000
